2023-02-24 23:40:22,568:DEBUG:certbot._internal.main:certbot version: 2.3.0
2023-02-24 23:40:22,568:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2023-02-24 23:40:22,568:DEBUG:certbot._internal.main:Arguments: ['--standalone', '--email', 'admin@ekipik.com', '--agree-tos', '--no-eff-email', '-d', 'ekipik.com']
2023-02-24 23:40:22,568:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2023-02-24 23:40:22,974:DEBUG:certbot._internal.log:Root logging level set at 30
2023-02-24 23:40:22,998:DEBUG:certbot._internal.plugins.selection:Requested authenticator standalone and installer None
2023-02-24 23:40:23,001:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * standalone
Description: Runs an HTTP server locally which serves the necessary validation files under the /.well-known/acme-challenge/ request path. Suitable if there is no HTTP server already running. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: standalone = certbot._internal.plugins.standalone:Authenticator
Initialized: <certbot._internal.plugins.standalone.Authenticator object at 0x7fb719d9ffa0>
Prep: True
2023-02-24 23:40:23,003:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.standalone.Authenticator object at 0x7fb719d9ffa0> and installer None
2023-02-24 23:40:23,004:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator standalone, Installer None
2023-02-24 23:40:23,071:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/981142156', new_authzr_uri=None, terms_of_service=None), b77255b35efceed86589ec77ef9de36d, Meta(creation_dt=datetime.datetime(2023, 2, 24, 21, 40, 1, tzinfo=<UTC>), creation_host='19659167250f', register_to_eff=None))>
2023-02-24 23:40:23,073:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2023-02-24 23:40:23,075:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2023-02-24 23:40:23,612:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 756
2023-02-24 23:40:23,614:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 24 Feb 2023 23:40:24 GMT
Content-Type: application/json
Content-Length: 756
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "Y4EHFNk59EQ": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/get/draft-ietf-acme-ari-00/renewalInfo/",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2023-02-24 23:40:23,620:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for ekipik.com
2023-02-24 23:40:23,629:DEBUG:acme.client:Requesting fresh nonce
2023-02-24 23:40:23,631:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2023-02-24 23:40:23,801:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2023-02-24 23:40:23,803:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 24 Feb 2023 23:40:24 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 15C9KfngsmeRbFBm9r-LlZCK2xzjbPnwr4XHFReAN7wLx0w
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2023-02-24 23:40:23,804:DEBUG:acme.client:Storing nonce: 15C9KfngsmeRbFBm9r-LlZCK2xzjbPnwr4XHFReAN7wLx0w
2023-02-24 23:40:23,806:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "ekipik.com"\n    }\n  ]\n}'
2023-02-24 23:40:23,809:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvOTgxMTQyMTU2IiwgIm5vbmNlIjogIjE1QzlLZm5nc21lUmJGQm05ci1MbFpDSzJ4empiUG53cjRYSEZSZUFON3dMeDB3IiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "UoxMX0nbZungZAAn4q8DMyHmCrtcw4QeTAzuBDYl0zgw1OxTxkaGV4xgRJQV_FdT8Sg2SJutFunt-bAf4x4XZO4vp2jj9v1jfEH7pWacddzb0rprObBHDEPCMGlnR4XUvQwG5kvVySnhLgg8yW8_CReMBpzZ4rxMqM9dvedbrt-NEGfn69sEuUgGWBaZP4AxyqFFl0hoYMkYvC1HlTawU54SdfDoP-yPkUzKQZAx2uOqb5pQpBoGiQHMoPy7IO5XnMTv8u99vUcgzTUG3YBAlPxEtQgYYC-l7LzySvJ0ixg49hjJeG07RvwcpN0rmDvHNYMwa00LY_Fh3hE52eBLsQ",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImVraXBpay5jb20iCiAgICB9CiAgXQp9"
}
2023-02-24 23:40:24,017:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 429 213
2023-02-24 23:40:24,019:DEBUG:acme.client:Received response:
HTTP 429
Server: nginx
Date: Fri, 24 Feb 2023 23:40:25 GMT
Content-Type: application/problem+json
Content-Length: 213
Connection: keep-alive
Boulder-Requester: 981142156
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 1DFAAcps_B6-pB1l2-QLh8XQtJvlWOp7CUobb1YAfx-_z-M

{
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/",
  "status": 429
}
2023-02-24 23:40:24,021:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1862, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1595, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 140, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 516, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 478, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem)
  File "/opt/certbot/src/acme/acme/client.py", line 138, in new_order
    response = self._post(self.directory['newOrder'], order)
  File "/opt/certbot/src/acme/acme/client.py", line 338, in _post
    return self.net.post(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 711, in post
    return self._post_once(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 724, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/opt/certbot/src/acme/acme/client.py", line 575, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/
2023-02-24 23:40:24,023:ERROR:certbot._internal.log:An unexpected error occurred:
2023-02-24 23:40:24,024:ERROR:certbot._internal.log:Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/
